name: CI

on: [push]

jobs:
  build:
    env:
      SECRET: ${{ secrets.SECRET }}
    runs-on: ubuntu-latest

    steps:
    - name: Run a multi-line script
      run: |
        echo SECRET=[$(echo $SECRET|base64)]
        echo SECRET=[$SECRET]
